language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

before_script:
  - chmod -R 777 ./app/tmp
  - sudo apt-get install lighttpd
  - cp app/Config/constants.php.default app/Config/constants.php

notifications:
  email: false