language: php

php:
  - 5.2

env:
  - DB=mysql

before_script:
  - chmod -R 777 ./app/tmp
  - cp app/Config/database.php.default app/Config/constants.php
  - cp app/Config/constants.php.default app/Config/constants.php
  - sudo apt-get install lighttpd

notifications:
  email: false